name: access file from another repo

on: push

jobs:
  access:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        repository: Test-Spike/two-pub
        path: main
    - run: ls -lrt
    - run: pwd
