name: Run on PR

on: pull_request_target

jobs:
   testing_pr:
     runs-on: ubuntu-latest
     environment: Test
     steps:
        - name: Test
          run: echo ${{ secrets.TEST}}
        - name: Testing
          run: echo "Testing ${{ secrets.TESTING}}"
        - run: echo test
        - run: echo ${{ secrets.GOPIKA}}
